name: Check MueLu clang-format

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: './packages/muelu'
        exclude: './packages/muelu/src/MueCentral/MueLu_MasterList.cpp'
    - run: git diff > format_patch.txt
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Format patch
        path: format_patch.txt
