# Run clang-tidy
name: Clang-tidy

on:
  pull_request:
    branches: [ master ]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run clang-tidy
      uses: HorstBaerbel/action-clang-tidy@1.2
      # These are optional (defaults displayed)
      with:
        scandir: './packages/muelu'
        builddir: 'build'
        excludedirs: ''
        extensions: 'cpp,hpp'
        cmakeoptions: ''