name: Run clang-format Linter

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: './packages/muelu'
        exclude: './lib'
        extensions: 'cpp,hpp'
        clangFormatVersion: 8
        inplace: False
